default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>
development:
  <<: *default
  database: smart_city_development
test:
  <<: *default
  database: smart_city_test
production:
  <<: *default

